services:
  # Service MySQL
  mysql:
    image: mysql:8.0
    container_name: GoArticle-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: GoArticleDB
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  # Service Adminer
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8081:8080"

  # Service aplikasi Golang
  app:
    build: .
    container_name: GoArticle
    ports:
      - "3000:3000"
    depends_on:
      - mysql

volumes:
  mysql_data:
